### ISSUE TITLE
context.dependOnInheritedWidgetOfExactType

### ISSUE THREAD

**Issue by kia1349** [sbis04/binary_clock#1]
Error: The method 'dependOnInheritedWidgetOfExactType' isn't defined for the class 'BuildContext'.

**Comment by sbis04** [comment]
This change is introduced in **Flutter verison 1.12**. You might be facing this because you are on a previous version of Flutter.

Please upgrade to the latest version using the command:
```dart
flutter upgrade
```
or, instead of using:
```dart
context.dependOnInheritedWidgetOfExactType<_CustomTheme>()
```
you can replace it with:
```dart
context.inheritFromWidgetOfExactType(_CustomTheme) as _CustomTheme
```
This will work with the previous versions of Flutter, but is **deprecated** in the **Flutter 1.12**

You can refer to the commit here: https://github.com/sbis04/binary_clock/commit/a2ceb908eed46588383cc543ca3c1c7bc77f6b2f

**Comment by Joe294ME** [comment]
upgrading flutter did the trick.  Thank you sbis04
